# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ParDistHMWKMNMelton

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://dockertesttest.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_9c244089c3fd4477a0b4f291741b10fe }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e3100089761c44a7a405b2615dff991c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_9c244089c3fd4477a0b4f291741b10fe }}/pardisthmwkmnmelton-img:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ParDistHMWKMNMelton'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_35afe4d2d16d4ee58ff42808fc4e5e88 }}
        images: 'dockertesttest.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9c244089c3fd4477a0b4f291741b10fe }}/pardisthmwkmnmelton-img:${{ github.sha }}'